routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'web'], function () {
    Route::get('/', function () {
        if(Auth::check())
            return redirect('/home');
        else
            return view('auth/login');
    })->name('landingPage');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'auth'], function () {
        //Headhunter menu
        Route::get('/createJobPost', 'PostJobController@showCreateJobForm')->name('showCreateJobForm');
        Route::post('/createJobPost', 'PostJobController@createJobPost')->name('createJobPost');
        Route::get('/viewMyPostedJob/{headhunter}', 'PostJobController@viewMyPostedJob')->name('viewMyPostedJob');
        Route::post('/JobPost/{jobpost}/Applicant/{jobseeker}/Accept', 'PostJobController@acceptApplication')->name('acceptApplication');
        Route::post('/JobPost/{jobpost}/Applicant/{jobseeker}/Reject', 'PostJobController@rejectApplication')->name('rejectApplication');

        //Jobseeker menu
        Route::get('/viewMyAppliedJob/{jobseeker}', 'PostJobController@viewMyAppliedJob')->name('viewMyAppliedJob');

        //Both headhunter and jobseeker
        Route::get('/JobPost/{jobpost}', 'PostJobController@viewJobPost')->name('viewJobPost');
        Route::post('/JobPost/{jobpost}/apply', 'PostJobController@applyJob')->name('applyJob');
        Route::get('/HeadhunterProfile/{headhunter}', 'ProfileController@viewHeadhunterProfile')->name('viewHeadhunterProfile');
        Route::get('/editProfile/{user}', 'ProfileController@editProfile')->name('editProfile');
        Route::put('/editProfile/{user}', 'ProfileController@updateProfile')->name('updateProfile');
        Route::get('/changePassword', 'ProfileController@changePassword')->name('changePassword');
        Route::post('/changePassword', 'ProfileController@storeNewPassword')->name('storeNewPassword');
        Route::post('/searchByTags', 'PostJobController@searchByTags')->name('searchByTags');
    });

});

app/Headhunter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Headhunter extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'company_telephone','company_address', 'company_website'
    ];

    protected $table = 'headhunters';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function jobposts()
    {
        return $this->hasMany(JobPost::class);
    }
}

app/Jobseeker.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Jobseeker extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'telephone','gender', 'experience','dateOfBirth'
    ];

    protected $table = 'jobseekers';

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['dateOfBirth'];

    public function getAgeAttribute()
    {
        return Carbon::now()->diffInYears($this->dateOfBirth);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function jobapplications()
    {
        return $this->hasMany(JobApplication::class);
    }

    function getDobAttribute()
    {
        return $this->dateOfBirth->toDateString();
    }

}

resources/views/headhunter/createJobPost.blade.php
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" type="text/css" href="/css/postJob.css">
    <link rel="stylesheet" href="/css/materialIcons.css">
    <link rel="stylesheet" href="/css/purple.min.css"/>
    <script defer src="/js/material.min.js"></script>
    <link rel="stylesheet" href="/css/getmdl-select.min.css"/>
    <script defer src="/js/getmdl-select.min.js"></script>
    <script defer src="/js/data-required.js"></script>
    <title>Create Job</title>

</head>

<body>
<div class="layout-waterfall mdl-layout mdl-js-layout">
    <header class="mdl-layout__header mdl-layout__header--waterfall">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <span class="mdl-layout-title"><a class="title-link" href="{{route('landingPage')}}">Part-time Job Online</a></span>
            <div class="mdl-layout-spacer"></div>

            <!-- menu button -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                @if(Auth::user()->role == "Job Seekers")
                    <a class="mdl-navigation__link" href="{{ route('viewMyAppliedJob',['jobseeker' => Auth::user()->jobseeker->id]) }}">View Applied Job</a>
                @else
                    <a class="mdl-navigation__link" href="{{ route('showCreateJobForm') }}">Create Job</a>
                    <a class="mdl-navigation__link" href="{{ route('viewMyPostedJob',['headhunter' => Auth::user()->headhunter->id]) }}">View Posted Job</a>
                @endif
                <a class="mdl-navigation__link" href="{{ route('editProfile',['user' => Auth::user()->id]) }}">Edit Profile</a>
                <a class="mdl-navigation__link" href="{{ route('logout') }}" onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();"> Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </nav>
        </div>
    </header>

    <main class="mdl-layout__content">
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--3-col"></div>
            <div class="mdl-cell mdl-cell--6-col">
                <div class="demo-card-wide mdl-card mdl-shadow--2dp">
                    <div class="mdl-card__title card__title">
                        <h2 class="mdl-card__title-text">Create Job</h2>
                    </div>
                    <div class="mdl-card__supporting-text text-in-card">

                        <form class="form-horizontal" method="POST" action="{{ route('createJobPost') }}">
                            {{ csrf_field() }}

                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                <input class="mdl-textfield__input" type="text" id="position-title" name="position-title" required>
                                <label class="mdl-textfield__label" for="position-title">Position Title</label>
                            </div>

                            <!-- Job location State for keyword search purpose-->
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
                                <input class="mdl-textfield__input" type="text" id="job-location-state" name="job-location-state" required tabIndex="-1" onchange="jobLocation()">
                                <label for="job-location-state">
                                    <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                                </label>
                                <label for="job-location-state" class="mdl-textfield__label">Job Location</label>
                                <ul for="job-location-state" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                                    <li class="mdl-menu__item">Kuala Lumpur</li>
                                    <li class="mdl-menu__item">Selangor</li>
                                    <li class="mdl-menu__item">Johor</li>
                                    <li class="mdl-menu__item">Penang</li>
                                    <li class="mdl-menu__item">Kedah</li>
                                    <li class="mdl-menu__item">Kelantan</li>
                                    <li class="mdl-menu__item">Labuan</li>
                                    <li class="mdl-menu__item">Melaka</li>
                                    <li class="mdl-menu__item">Negeri Sembilan</li>
                                    <li class="mdl-menu__item">Pahang</li>
                                    <li class="mdl-menu__item">Perak</li>
                                    <li class="mdl-menu__item">Perlis</li>
                                    <li class="mdl-menu__item">Putrajaya</li>
                                    <li class="mdl-menu__item">Sabah</li>
                                    <li class="mdl-menu__item">Sarawak</li>
                                    <li class="mdl-menu__item">Terengganu</li>
                                </ul>
                            </div>

                            <!-- User input job location -->
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label location-toggle" id='job-location-exact'>
                                <input class="mdl-textfield__input" type="text" id="job-location-exact" name="job-location-exact" required>
                                <label class="mdl-textfield__label" for="job-location-exact">Exact Location</label>
                            </div>


                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                <input class="mdl-textfield__input" type="text" id="dresscode" name="dresscode" required>
                                <label class="mdl-textfield__label" for="dresscode">Dresscode</label>
                            </div>

                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
                                <input class="mdl-textfield__input" type="text" id="language" name="language" tabIndex="-1" required>
                                <label for="language">
                                    <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                                </label>
                                <label for="language" class="mdl-textfield__label">Language</label>
                                <ul for="language" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                                    <li class="mdl-menu__item" data-val="EN">English</li>
                                    <li class="mdl-menu__item" data-val="CH">Chinese</li>
                                    <li class="mdl-menu__item" data-val="MY">Malay</li>
                                    <li class="mdl-menu__item" data-val="TM">Tamil</li>
                                    <li class="mdl-menu__item" data-val="OT">Others</li>
                                </ul>
                            </div>

                            <div class="display-block">
                                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label salary">
                                    <input class="mdl-textfield__input salary-align" type="text" pattern="[0-9]{1,25}" id="salary-money" name="salary-money" required>
                                    <label class="mdl-textfield__label" for="salary-money">Salary (RM)</label>
                                    <span class="mdl-textfield__error">Input is not a number!</span>
                                </div>
                                /
                                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                                    <input class="mdl-textfield__input" type="text" id="salary-period" name="salary-period" tabIndex="-1" required>
                                    <label for="salary-period">
                                        <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                                    </label>
                                    <label for="salary-period" class="mdl-textfield__label">Per period</label>
                                    <ul for="salary-period" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                                        <li class="mdl-menu__item" data-val="1">hour</li>
                                        <li class="mdl-menu__item" data-val="2">day</li>
                                        <li class="mdl-menu__item" data-val="3">week</li>
                                        <li class="mdl-menu__item" data-val="4">month</li>
                                        <li class="mdl-menu__item" data-val="5">year</li>
                                        <li class="mdl-menu__item" data-val="6">event</li>
                                    </ul>
                                </div>
                            </div>


                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label display-block">
                                <input class="mdl-textfield__input" type="text" id="working-hours" name="working-hours" required>
                                <label class="mdl-textfield__label" for="working-hours">Working Hours</label>
                            </div>

                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                <textarea class="mdl-textfield__input" type="text" rows= "4" id="job-description" name="job-description" required></textarea>
                                <label class="mdl-textfield__label" for="job-description">Job Description</label>
                            </div>

                            <!-- Submit button -->
                            <div class="post-btn">
                                {{--<div class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary" type="submit" onclick="submitValidation()">--}}
                                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary" type="submit">
                                Post Job
                                </button>
                                {{--</div>--}}
                            </div>

                        </form>

                        @if (count($errors))
                            <div class="alert alert-danger fade in m-b-15">
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                    </div>
                </div>
            </div>
        </div>
</main>
</div>
<script src="/js/date-input-polyfill.js"></script>
<script>
    // Validation function
    //need to do complete form function also
    function submitValidation(){
        if (document.getElementById("first-name").value != '') {
            alert("HEL");
        }
        else  {
            var d = document.getElementById("first-name");
            d.className += " is-invalid";
        }
    }

    //Job Location
    function jobLocation(){
        document.getElementById("job-location-exact").style.display = 'inline-block';
    }

</script>
</body>
</html>

resources/views/headhunter/profile.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="/css/viewProfile.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <link rel="stylesheet" href="/css/materialIcons.css">
    <link rel="stylesheet" href="/css/purple.min.css"/>
    <script defer src="/js/material.min.js"></script>
    <title>View Headhunter Profile</title>

</head>

<body>
<div class="layout-waterfall mdl-layout mdl-js-layout">
    <header class="mdl-layout__header mdl-layout__header--waterfall">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <span class="mdl-layout-title"><a class="title-link"
                                              href="{{route('landingPage')}}">Part-time Job Online</a></span>
            <div class="mdl-layout-spacer"></div>

            <!-- menu button -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                @if(Auth::user()->role == "Job Seekers")
                    <a class="mdl-navigation__link" href="{{ route('viewMyAppliedJob',['jobseeker' => Auth::user()->jobseeker->id]) }}">View Applied Job</a>
                @else
                    <a class="mdl-navigation__link" href="{{ route('showCreateJobForm') }}">Create Job</a>
                    <a class="mdl-navigation__link" href="{{ route('viewMyPostedJob',['headhunter' => Auth::user()->headhunter->id]) }}">View Posted Job</a>
                @endif
                <a class="mdl-navigation__link" href="{{ route('editProfile',['user' => Auth::user()->id]) }}">Edit Profile</a>
                <a class="mdl-navigation__link" href="{{ route('logout') }}" onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();"> Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </nav>
        </div>
    </header>


    <main class="mdl-layout__content">
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--3-col"></div>
            <div class="mdl-cell mdl-cell--6-col">
                <div class="demo-card-wide mdl-card mdl-shadow--2dp">
                    <div class="mdl-card__title card__title">
                        <h2 class="mdl-card__title-text">View Headhunter Profile</h2>
                    </div>
                    <div class="mdl-card__supporting-text text-in-card">

                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" id="name" value="{{$headhunter->user->name}}" readonly>
                            <label class="mdl-textfield__label" for="first-name">Company Name</label>
                        </div>

                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" id="email" value="{{$headhunter->user->email}}" readonly>
                            <label class="mdl-textfield__label" for="email">Email Address</label>
                        </div>

                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="tel" pattern="-?[0-9]*(\.[0-9]+)?" id="phone_number" value="{{$headhunter->company_telephone}}" readonly>
                            <label class="mdl-textfield__label" for="phone_number">Telephone Number</label>
                        </div>

                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" id="website" value="{{$headhunter->company_website}}" readonly>
                            <label class="mdl-textfield__label" for="gender">Company Website</label>
                        </div>

                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" id="address" value="{{$headhunter->company_address}}" readonly>
                            <label class="mdl-textfield__label" for="gender">Company Address</label>
                        </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
</main>
</div>
</body>
</html>

resources/views/headhunter/viewMyPostedJob.blade.php
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" type="text/css" href="/css/viewApplicant.css">
    <link rel="stylesheet" href="/css/materialIcons.css">
    <link rel="stylesheet" href="/css/purple.min.css"/>
    <script defer src="/js/material.min.js"></script>
    <title>View Job Applicants</title>

</head>

<body>
<div class="layout-waterfall mdl-layout mdl-js-layout" id="allPostedJobContainer">
    <header class="mdl-layout__header mdl-layout__header--waterfall">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <span class="mdl-layout-title">
                <a class="title-link" href="{{route('landingPage')}}">Part-time Job Online</a>
            </span>
            <div class="mdl-layout-spacer"></div>

            <!-- menu button -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                @if(Auth::user()->role == "Job Seekers")
                    <a class="mdl-navigation__link"
                       href="{{ route('viewMyAppliedJob',['jobseeker' => Auth::user()->jobseeker->id]) }}">View Applied
                        Job</a>
                @else
                    <a class="mdl-navigation__link" href="{{ route('showCreateJobForm') }}">Create Job</a>
                    <a class="mdl-navigation__link"
                       href="{{ route('viewMyPostedJob',['headhunter' => Auth::user()->headhunter->id]) }}">View Posted
                        Job</a>
                @endif
                <a class="mdl-navigation__link" href="{{ route('editProfile',['user' => Auth::user()->id]) }}">Edit
                    Profile</a>
                <a class="mdl-navigation__link" href="{{ route('logout') }}" onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();"> Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </nav>
        </div>
    </header>


    <main class="mdl-layout__content">
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--2-col"></div>
            <div class="mdl-cell mdl-cell--8-col">
                <div class="page-title">
                    <h4>View Job Applicants</h4>
                </div>

                @foreach($jobposts as $jobpost)
                    <div id="job_post_{{$jobpost->id}}">
                        <div class="mdl-list__item job-title-list">
                            <span class="mdl-list__item-primary-content">{{$jobpost->title}}</span>
                            <span class="mdl-list__item-secondary-content pointer"
                                  onclick="toggleInfo({{$jobpost->id}})">
								<i class="material-icons">info</i>
							</span>
                            <span class="mdl-list__item-secondary-content pointer"
                                  onclick="toggleApplicantList({{$jobpost->id}})">
								<i class="material-icons">expand_more</i>
							</span>
                        </div>
                        <div id="job_info_{{$jobpost->id}}" style="display:none">
                            <div class="mdl-card__supporting-text">
                                <p><strong>Job Location: </strong>{{$jobpost->location}}</p>
                                <p><strong>Working Hours: </strong>{{$jobpost->working_hours}}</p>
                                <p><strong>Salary: </strong>{{$jobpost->salary}}</p>
                                <p><strong>Language: </strong>{{$jobpost->language}}</p>
                                <p><strong>Dresscode: </strong>{{$jobpost->dress_code}}</p>
                                <p><strong>Description: </strong> {{$jobpost->description}}</p>
                            </div>
                        </div>
                        <div id="job_applicants_{{$jobpost->id}}" class="applicant-list" style="display:none">
                            <ul class="demo-list-icon mdl-list">
                                {{--applicant list--}}
                                @foreach($jobpost->jobapplications as $jobapplication)
                                    <li class="mdl-list__item mdl-list__item--three-line">
                                        <span class="demo-list-width mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-avatar">person</i>
                                            <span>{{$jobapplication->jobseeker->user->name}}</span>
                                            <span class="supporting-details">{{$jobapplication->jobseeker->gender}}</span>
                                            <span class="supporting-details">{{$jobapplication->jobseeker->age}}</span>
                                            <span class="supporting-details">{{$jobapplication->jobseeker->telephone}}</span>
                                            <span class="mdl-list__item-text-body">{{$jobapplication->jobseeker->experience}}</span>
                                        </span>
                                        <span class="mdl-list__item-secondary-content">
                                            <span class="mdl-list__item-secondary-info"></span>
                                            @if($jobapplication->status == "pending" )
                                            <div class="status-bar">
                                                <form action="{{route('acceptApplication',['jobpost' => $jobpost->id, 'jobseeker' => $jobapplication->jobseeker->id])}}"
                                                      method="POST">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <button id="accept"
                                                            class="mdl-button mdl-js-button mdl-button--primary mdl-button--raised accept-btn"
                                                            type="submit">
                                                        Accept
                                                    </button>
                                                </form>
                                                <form action="{{route('rejectApplication',['jobpost' => $jobpost->id, 'jobseeker' => $jobapplication->jobseeker->id])}}"
                                                      method="POST">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <button id="reject"
                                                            class="mdl-button mdl-js-button mdl-button--primary mdl-button--raised reject-btn"
                                                            type="submit">
                                                        Reject
                                                    </button>
                                                </form>
                                            </div>
                                            @else
                                                <div class="mdl-button mdl-js-button mdl-button--raised">
                                                    {{$jobapplication->status}}
                                                </div>
                                            @endif                                           
									    </span>

                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </main>
    @if (session('status'))
        <div class="mdl-js-snackbar mdl-snackbar mdl-snackbar--active">
            <div class="mdl-snackbar__text">
                {{ session('status') }}
            </div>
            <button class="mdl-snackbar__action" type="button"></button>
        </div>
    @endif
</div>
<script>

    function toggleApplicantList(id) {
        var x = document.getElementById("job_applicants_" + id);
        if (x.style.display !== 'block') {
            x.style.display = 'block';
        }
        else {
            x.style.display = 'none';
        }
    }

    function toggleInfo(id) {
        var x = document.getElementById("job_info_" + id);
        if (x.style.display !== 'block') {
            x.style.display = 'block';
        }
        else {
            x.style.display = 'none';
        }
    }

</script>
</body>
</html>